server:
  port: 8086
logging:
  level:
    com.entdiy: DEBUG
    io.netty.handler.logging: INFO
    root: INFO
  config: classpath:logback-spring-dev.xml
nat:
  clientId: ABC-EDF
  clientSecret: 123456

  #serverAddr: entdiy.com
  #port: 5555
  serverAddr: 127.0.0.1
  port: 4443
  # 穿透通道定义模式：
  # client = 客户端本地tunnels配置为准，忽略server端配置
  # server = server端定义为准，忽略本地tunnels配置
  tunnelsMode: "client"
  tunnels:
    ssh-test:
      host: 127.0.0.1
      port: 22
      remotePort: 122
    hik-test:
      host: 25.30.14.64
      port: 8000
      remotePort: 18000
    mysql:
      host: 127.0.0.1
      port: 3306
      remotePort: 13306
    redis:
      host: 127.0.0.1
      port: 6379
      remotePort: 16379
    tester-tcp:
      host: 127.0.0.1
      port: 8888
      remotePort: 18888
    tester-http:
      proto: http
      host: 127.0.0.1
      port: 8088
      remotePort: 18088
