server:
  port: 8086
  servlet:
    context-path: /nat
spring:
  profiles:
    include: nat-client
nat:
  idlePingEnabled: false
  clientId: ABC-EDF
  clientSecret: 123456
  version: 1.1.0
  mmVersion: C20201212

  serverAddr: 127.0.0.1
  port: 4443
  tunnels:
    - name: ssh-test
      host: 25.30.9.146
      port: 22
      remotePort: 18068
    - name: hik-test
      host: 25.30.14.64
      port: 8000
      remotePort: 18070
    - name: hik-001-001
      host: 127.0.0.1
      port: 3306
      remotePort: 18075
    - name: hik-001-002
      host: 127.0.0.1
      port: 6379
      remotePort: 18074
    - name: tester
      host: 127.0.0.1
      port: 8888
      remotePort: 18073
