server:
  port: 8080
  servlet:
    context-path: /nat
spring:
  main:
    banner-mode: off
  application:
    name: entdiy-nat-client
  profiles:
    include: client
    active: dev
nat:
  version: 1.1.0
  mmVersion: C20201212
