logging:
  level:
    com.entdiy: DEBUG
    io.netty.handler.logging: INFO
    root: INFO
  config: classpath:logback-spring-dev.xml
nat:
  domain: 127.0.0.1
  httpAddr: 80
  httpsAddr: 443
  tunnelAddr: 4443
