server:
  port: 8090
  servlet:
    context-path: /nat
spring:
  main:
    banner-mode: off
  application:
    name: entdiy-nat-server
  profiles:
    include: server,local
    active: dev
logging:
  config: classpath:logback-spring-prd.xml
nat:
  sslAuth: false
  keyStorePass: entdiy-nat
  version: 1.0.0
  mmVersion: S20201212
