server:
  port: 8090
  servlet:
    context-path: /nat
spring:
  profiles:
    include: nat-server
nat:
  domain: localhost
  httpAddr: 80
  httpsAddr: 443
  tunnelAddr: 4443
  version: 1.0.0
  mmVersion: S20201212
