server:
  port: 8090
  servlet:
    context-path: /nat
spring:
  application:
    name: entdiy-nat-client
  profiles:
    include: server
nat:
  domain: 127.0.0.1
  httpAddr: 80
  httpsAddr: 443
  tunnelAddr: 4443
  version: 1.0.0
  mmVersion: S20201212
