server:
  # Web管理端口，默认0表示随机端口(可通过启动日志查看运行端口)，亦可设定为当前机器空闲固定网络端口
  port: 0
logging:
  level:
    root: INFO
nat:
  clientId:
  clientSecret:

  serverAddr: 127.0.0.1
  port: 4443
  # 穿透通道定义模式：
  # client = 客户端本地tunnels配置为准，忽略server端配置
  # server = server端定义为准，忽略本地tunnels配置
  tunnelsMode: "client"
  tunnels:
    mock:
      host: 127.0.0.1
      port: 22
      remotePort: 2222
